default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password:

development:
  <<: *default
  database: worknote_development

test:
  <<: *default
  database: worknote_test

production:
  <<: *default
  database: worknote_production
  username: worknote
  password: <%= ENV['WORKNOTE_DATABASE_PASSWORD'] %>
